/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package common;

import java.time.LocalDateTime;

/**
 * Represents a user's <em>profile</em>, which contains stable information that is
 * specific to that user, but not stored within the user database.
 * 
 * @author Gryphon Ayers (2019)
 */
public class Profile {
    private final int profileID; // primary key - autogenerated
    private int profileUser; // foreign key - references a BuUser ID
    private String campusPhone;
    private int yearsOfService;
    private String rank;
    private LocalDateTime appointmentDate;
    private LocalDateTime lastPromotionDate;
    private int lastApplication; // foreign key - references applicationID

    public Profile(int profileID) {
        this.profileID = profileID;
    }

    public int getProfileID() {
        return profileID;
    }

    public int getProfileUser() {
        return profileUser;
    }

    public void setProfileUser(int profileUser) {
        this.profileUser = profileUser;
    }

    public String getCampusPhone() {
        return campusPhone;
    }

    public void setCampusPhone(String campusPhone) {
        this.campusPhone = campusPhone;
    }

    public int getYearsOfService() {
        return yearsOfService;
    }

    public void setYearsOfService(int yearsOfService) {
        this.yearsOfService = yearsOfService;
    }

    public String getRank() {
        return rank;
    }

    public void setRank(String rank) {
        this.rank = rank;
    }

    public LocalDateTime getAppointmentDate() {
        return appointmentDate;
    }

    public void setAppointmentDate(LocalDateTime appointmentDate) {
        this.appointmentDate = appointmentDate;
    }

    public LocalDateTime getLastPromotionDate() {
        return lastPromotionDate;
    }
    
    public void setLastPromotionDate(LocalDateTime lastPromotionDate) {
        this.lastPromotionDate = lastPromotionDate;
    }

    public int getLastApplication() {
        return lastApplication;
    }

    public void setLastApplication(int lastApplication) {
        this.lastApplication = lastApplication;
    }
}
